server:
  port: 8300

logging:
  level:
    root: info
    com.ylsm.*: DEBUG


spring:
  application:
    name: ylsm-api-docking

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost\MSSQLSERVER:1433;database=ylsm_api_docking;encrypt=false
    username: sa
    password: zxcvbnm
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Chongqing

feign:
  host: http://ylsm.api.ing:40002/mps-interfaces
  name: client
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 30000

docking:
  account: account
  password: password
  token:
    expire:
      limit: 90 # 60 分钟过期一次
  api:
    module:
      token:
        route: /token/getTokenInfo
      updateStock:
        route: /outer/updateStock
        method: updateStock
      saleSheet:
        route: /outer/saleSheet
        method: saleSheet
      cloundSender:
        route: /outer/cloundSender
        method: cloundSender
      productInfoSender:
        route: /outer/productInfoSender
        method: productInfoSender
      postProductSender:
        route: /outer/postProductSender
        method: postProductSender
      rejectProductSender:
        route: /outer/rejectProductSender
        method: rejectProductSender